name: Java CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'              

        - name: Start mysql
          run: sudo /etc/init.d/mysql start 

        - name: Set up the database  
          run: mysql -uroot -proot < sql/create-productsdb.sql 

        - name: Prepare tables with datanucleus  
          run: mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create

        - name: include options for performance tests
          run: set JDK_JAVA_OPTIONS=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED

        - name: Build with Maven including tests
          run: mvn --batch-mode --update-snapshots test